## Preprocessing Nigeria trip data

In [77]:
import pandas as pd
import numpy as np
import datetime
import time
import os
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
%config InlineBackend.figure_format='retina'
sns.set() # Revert to matplotlib defaults
plt.rcParams['figure.figsize'] = (16, 12)
plt.rcParams['axes.labelpad'] = 10
sns.set_style("darkgrid")

In [78]:
# price = pd.read_csv('nigeria-intratrip-data-v1-0-0.csv')
price = pd.read_csv('nigeria-intratrip-data-v1-0-1.csv')

In [79]:
price.sample(10) # date[months], 2020-2021, remove outliers, || number of trucks, trip/truck

,Unnamed: 0,__v,_id_x,actualTripDuration__id,actualTripDuration_text,actualTripDuration_value,asset__id,asset_id,asset_name,asset_size,...,source_region,destination,destination_region,sourcecountry,destinationcountry,unit,goodType,goodCategory,currency,amount
1656,11070,0,5fec45875f790c005d125bdc,5fec45875f790c005d125bde,"17 days, 14 hours, 16 minutes, 55 seconds",1520215.538,5fd51202799d2b00825af32f,5c8588ead1a641000ddf3605,Flatbed,40.0,...,south west,LAGOS,south west,NIGERIA,NIGERIA,FT,OTHERS,OTHERS,NGN,311750.00
3808,19747,0,6101ad406333f100a28e2922,6101ad406333f100a28e2924,"5 days, 23 hours, 33 minutes, 34 seconds",516814.576,60d5a09e73b9b80178b98515,5c8588efd1a641000ddf360b,Covered,15.0,...,south west,DELTA,south south,NIGERIA,NIGERIA,TONS,FMCG,VEGETABLE OIL,NGN,258553.57
8945,28186,0,6161bdf84fab68004e3f2ca5,6161bdf84fab68004e3f2ca7,"14 days, 20 hours, 8 minutes, 31 seconds",1282111.514,6161bd1d4fab68004e3f2926,5c8588efd1a641000ddf360b,Covered,15.0,...,south west,DELTA,south south,NIGERIA,NIGERIA,TONS,VEGETABLE OIL,FMCG,NGN,274818.42
11010,31313,0,6187d0a3c5024700700a2cdf,6187d0a3c5024700700a2ce1,"1 day, 22 hours, 25 minutes, 52 seconds",167152.490,61853d48c5024700700106f0,5c8588ecd1a641000ddf3607,Open,30.0,...,south west,KWARA,north central,NIGERIA,NIGERIA,TONS,SOYA MILLS,FMCG,NGN,180000.00
9701,29180,0,616de586c5024700708b299a,616de586c5024700708b299c,"6 days, 11 hours, 41 minutes, 14 seconds",560474.212,61682281c5024700706871fc,5c8588ecd1a641000ddf3607,Open,30.0,...,south west,OYO,south west,NIGERIA,NIGERIA,TONS,SOYABEAN SEEDS,AGRO,NGN,107000.00
264,990,0,5f8182e57d7df80055821730,5f8182e57d7df80055821732,"4 days, 17 hours, 8 minutes, 37 seconds",407317.077,5f289e91dae4143733e60d18,5c8588ecd1a641000ddf3607,Open,30.0,...,south west,KWARA,north central,NIGERIA,NIGERIA,TONS,MAIZE PELLETS,AGRO,NGN,420000.00
1605,10990,0,5fec192b5f790c005d0ee3df,5fec192b5f790c005d0ee3e1,"13 days, 11 hours, 7 minutes, 39 seconds",1163259.667,5fda53acc0851b2380b1f435,5c8588ead1a641000ddf3605,Flatbed,40.0,...,south west,LAGOS,south west,NIGERIA,NIGERIA,FT,OTHERS,OTHERS,NGN,311750.00
6875,24948,0,613b70b0a72c70008b2abf6e,613b70b0a72c70008b2abf70,"12 days, 20 hours, 5 minutes, 7 seconds",1109107.680,6135e33b917b4f00a2d6084d,5c8588ecd1a641000ddf3607,Open,30.0,...,south west,KANO,north west,NIGERIA,NIGERIA,TONS,VEDAN,FOODS,NGN,750000.00
11283,31795,0,618e26d2c5024700702984a8,618e26d2c5024700702984aa,"12 hours, 31 minutes, 54 seconds",45114.769,618d4e47c50247007025ebed,5c8588ecd1a641000ddf3607,Open,30.0,...,south west,LAGOS,south west,NIGERIA,NIGERIA,TONS,FLOUR,FMCG,NGN,159715.00
7604,26127,0,6149d0e219ac5501209aa254,6149d0e219ac5501209aa256,"6 minutes, 47 seconds",407.883,6149af3e06a597010954b5de,5c8588efd1a641000ddf360c,Covered,10.0,...,south west,OGUN,south west,NIGERIA,NIGERIA,TONS,WINE AND SPIRIT,FMCG,NGN,35000.00

In [80]:
price.columns

Index(['Unnamed: 0', '__v', '_id_x', 'actualTripDuration__id',
       'actualTripDuration_text', 'actualTripDuration_value', 'asset__id',
       'asset_id', 'asset_name', 'asset_size', 'asset_type', 'asset_unit',
       'customerId', 'deliveryDate', 'deliveryLocation__id',
       'deliveryLocation_address', 'deliveryLocation_coordinates_lat',
       'deliveryLocation_coordinates_lon', 'deliveryLocation_type', 'driverId',
       'expectedETA__id', 'expectedETA_text', 'expectedETA_value',
       'lastKnownLocation', 'lastKnownLocation__id',
       'lastKnownLocation_address', 'lastKnownLocation_coordinates_lat',
       'lastKnownLocation_coordinates_lon', 'lastKnownLocation_country',
       'lastKnownLocation_geohash', 'lastKnownLocation_state',
       'lastKnownLocation_type', 'late', 'lateTime', 'loadedDate', 'partnerId',
       'pickupLocation__id', 'pickupLocation_address',
       'pickupLocation_coordinates_lat', 'pickupLocation_coordinates_lon',
       'pickupLocation_type', 'regNumber', 'remainingETA', 'remainingETA__id',
       'remainingETA_text', 'remainingETA_value', 'startDate', 'totalDistance',
       'tripId_x', 'tripReadId', '_id_y', 'tripId_y', 'partnerName',
       'deliveryStation_address', 'loaded_date', 'cargoTonnage', 'distance',
       'source', 'source_region', 'destination', 'destination_region',
       'sourcecountry', 'destinationcountry', 'unit', 'goodType',
       'goodCategory', 'currency', 'amount'],
      dtype='object')

In [81]:
price.shape

(13228, 68)

In [82]:
# list(price.columns)
new_price = price[['tripReadId','partnerName', 'source_region', 'loadedDate', 'destination_region', 'source',
       'destination', 'amount', 'goodType', 'asset_size', 'distance', 'totalDistance', 'cargoTonnage', 'currency', 'asset_type']]

In [83]:
new_price.sample(5)

,tripReadId,partnerName,source_region,loadedDate,destination_region,source,destination,amount,goodType,asset_size,distance,totalDistance,cargoTonnage,currency,asset_type
8716,TP1159060,ZDAN TRANSPORT,north west,2021-09-16T14:15:00.000Z,south west,KANO,LAGOS,340000.00,OTHERS,30.0,NaN,1078686.0,30.0,NGN,Open
4370,TP1153313,OLOLADE GOD'S MERCY MULTIPURPOSE VENTURE,south west,2021-08-04T08:40:00.000Z,south west,LAGOS,LAGOS,125031.53,OTHERS,20.0,NaN,22755.0,20.0,NGN,Covered
12742,TP1167493,Emaviv international services,south west,2021-12-06T05:34:00.000Z,south west,OGUN,OYO,117420.00,WINE AND SPIRIT,15.0,NaN,153185.0,12.0,NGN,Covered
6168,TP1156385,Shezlad Agrovet Venture,south west,2021-08-26T19:56:00.000Z,south west,OGUN,LAGOS,82400.00,WINE AND SPIRIT,15.0,NaN,46687.0,12.0,NGN,Covered
6406,TP1156606,Great heritage maritime ser ltd,south south,2021-08-28T16:59:00.000Z,south west,RIVERS,LAGOS,400000.00,FERTILIZER,30.0,NaN,613231.0,30.0,NGN,Open

In [84]:
new_price.isnull().sum()

tripReadId                0
partnerName               0
source_region             0
loadedDate                0
destination_region        0
source                    0
destination               0
amount                    0
goodType                  0
asset_size                6
distance              12006
totalDistance             0
cargoTonnage              0
currency                  0
asset_type                6
dtype: int64

In [85]:
new_price.source_region.unique()

array(['south west', 'north central', 'south south', 'north west',
       'south east', 'north east'], dtype=object)

In [86]:
new_price.destination_region.unique()

array(['south west', 'south south', 'north central', 'south east',
       'north west', 'north east'], dtype=object)

In [87]:
price['source'].unique()

array(['LAGOS', 'OGUN', 'OYO', 'KOGI', 'RIVERS', 'KADUNA', 'CROSS RIVER',
       'PLATEAU', 'KANO', 'ANAMBRA', 'ABIA', 'ONDO', 'AKWA IBOM', 'NIGER',
       'EDO', 'BENUE', 'GOMBE', 'KEBBI', 'FEDERAL CAPITAL TERRITORY',
       'ADAMAWA', 'KWARA', 'DELTA', 'OSUN', 'EBONYI', 'EKITI', 'ENUGU',
       'KATSINA'], dtype=object)

In [88]:
source_li=['KEBBI', 'KANO', 'LAGOS', 'OYO', 'KOGI', 'DELTA', 'RIVERS', 'KADUNA', 'OGUN', 'ANAMBRA',
    'CROSS RIVER', 'PLATEAU', 'KWARA', 'KATSINA', 'ADAMAWA', 'ABIA', 'NIGER', 'FEDERAL CAPITAL TERRITORY',
    'BENUE', 'EDO', 'OSUN', 'BORNO', 'IMO', 'ENUGU', 'EKITI', 'ONDO', 'NASARAWA', 'YOBE', 'ZAMFARA', 'SOKOTO', 
    'GOMBE', 'BAUCHI', 'JIGAWA', 'AKWA IBOM', 'BAYELSA', 'TARABA']

dest_li=['KEBBI', 'KANO', 'LAGOS', 'OYO', 'KOGI', 'DELTA', 'RIVERS', 'KADUNA', 'OGUN', 'ANAMBRA',
    'CROSS RIVER', 'PLATEAU', 'KWARA', 'KATSINA', 'ADAMAWA', 'ABIA', 'NIGER', 'FEDERAL CAPITAL TERRITORY',
    'BENUE', 'EDO', 'OSUN', 'BORNO', 'IMO', 'ENUGU', 'EKITI', 'ONDO', 'NASARAWA', 'YOBE', 'ZAMFARA', 'SOKOTO', 
    'GOMBE', 'BAUCHI', 'JIGAWA', 'AKWA IBOM', 'BAYELSA', 'TARABA']

new_price = new_price[new_price.source.isin(source_li)]
new_price = new_price[new_price.destination.isin(dest_li)]

In [89]:
new_price['source'].unique()

array(['LAGOS', 'OGUN', 'OYO', 'KOGI', 'RIVERS', 'KADUNA', 'CROSS RIVER',
       'PLATEAU', 'KANO', 'ANAMBRA', 'ABIA', 'ONDO', 'AKWA IBOM', 'NIGER',
       'EDO', 'BENUE', 'GOMBE', 'KEBBI', 'FEDERAL CAPITAL TERRITORY',
       'ADAMAWA', 'KWARA', 'DELTA', 'OSUN', 'EKITI', 'ENUGU', 'KATSINA'],
      dtype=object)

In [90]:
new_price['destination'].unique()

array(['LAGOS', 'EDO', 'DELTA', 'OGUN', 'PLATEAU', 'RIVERS',
       'FEDERAL CAPITAL TERRITORY', 'NIGER', 'OYO', 'KWARA', 'ABIA',
       'SOKOTO', 'KANO', 'ONDO', 'ENUGU', 'NASARAWA', 'IMO', 'GOMBE',
       'ANAMBRA', 'OSUN', 'EKITI', 'JIGAWA', 'KADUNA', 'ADAMAWA',
       'AKWA IBOM', 'CROSS RIVER', 'BORNO', 'KATSINA', 'YOBE', 'ZAMFARA',
       'KOGI', 'TARABA', 'BENUE', 'KEBBI', 'BAYELSA', 'BAUCHI'],
      dtype=object)

In [91]:
new_price.isnull().sum()

tripReadId                0
partnerName               0
source_region             0
loadedDate                0
destination_region        0
source                    0
destination               0
amount                    0
goodType                  0
asset_size                6
distance              11971
totalDistance             0
cargoTonnage              0
currency                  0
asset_type                6
dtype: int64

In [92]:
new_price['asset_type'].unique()

array(['Flatbed', 'Open', 'Covered', 'covered', 'Tipper', nan,
       '2x flatbed', 'Box'], dtype=object)

In [93]:
new_price['goodType'].unique()

array(['OTHERS', 'FMCG', 'DRINKS', 'MAIZE PELLETS', 'AGRO', 'SUGAR',
       'FLOUR', 'SOYA MILLS', 'HOUSEHOLD AND OFFICE', 'INDUSTRIAL',
       'RAW MATERIALS', 'SEMO', 'PASTA', 'BUILDING MATERIALS',
       'SOYABEAN SEEDS', 'EQUIPMENT', 'BEVERAGES AND DRINKS',
       'WINE AND SPIRIT', 'COAL', 'PHARMACEUTICAL', 'DETERGENT',
       'FERTILIZER', 'ANIMAL FEED',
       'HOUSEHOLD ITEMS (AC, FURNITURES,UTENSILS, ETC)',
       'AGROCHEMICAL PRODUCTS', 'RICE', 'FISH FEED',
       'CHEMICAL RAW MATERIALS', 'EQUIPMENTS', 'COTTON SEED', 'BEVERAGES',
       'OIL AND GAS', 'CLINKA', 'POULTRY', 'WHEAT', 'SORGHUM', 'NOODLES',
       'VEDAN', 'SAUSAGE', 'VEGETABLE OIL', 'OIL/LUBE', 'SESAME SEED',
       'TOMATO PASTE', 'GYPSUM', 'COCOA', 'CHEMICAL', 'DAIRY PRODUCTS',
       'ELECTRICALS', 'BLACK CARBON'], dtype=object)

In [94]:
#Feature Engineering of Time Series Column
new_price['loadedDate'] = pd.to_datetime(new_price['loadedDate'], format='%Y-%m-%d')
new_price['year'] = new_price['loadedDate'].dt.year
new_price['month'] = new_price['loadedDate'].dt.month
new_price['day'] = new_price['loadedDate'].dt.day

In [95]:
new_price.columns

Index(['tripReadId', 'partnerName', 'source_region', 'loadedDate',
       'destination_region', 'source', 'destination', 'amount', 'goodType',
       'asset_size', 'distance', 'totalDistance', 'cargoTonnage', 'currency',
       'asset_type', 'year', 'month', 'day'],
      dtype='object')

In [96]:
new_price['year'].unique()

array([2020, 2021])

In [97]:
year_list = [2020., 2021.]

#year_list = list(new_price['year'].unique())
new_price = new_price[new_price.year.isin(year_list)]

In [98]:
new_price['year'].unique()

array([2020, 2021])

In [99]:
new_price= new_price[['tripReadId', 'partnerName', 'cargoTonnage', 'asset_type', 'loadedDate', 'source_region','destination_region', 'source', # 'size', 'unit','delivered', 'goodCategory', destination_region','source_region'
                        'destination', 'goodType', 'asset_size', 'distance', 'totalDistance', 'year', 'month', 'currency', 'amount']] #'fleetAsset_unit', 'asset class', 'size.1', 'unit.1', 'type'

In [100]:
new_price.sample(10)

,tripReadId,partnerName,cargoTonnage,asset_type,loadedDate,source_region,destination_region,source,destination,goodType,asset_size,distance,totalDistance,year,month,currency,amount
12992,TP1167642,JACH TRISTAN GLOBAL SERVICES LTD,39.73,Open,2021-12-05 08:56:00+00:00,south south,north east,CROSS RIVER,GOMBE,CLINKA,40.0,NaN,1.086460e+06,2021,12,NGN,874060.0
9417,TP1160797,SIF-LOGISTICS,43.49,Open,2021-09-30 05:14:00+00:00,south south,north east,CROSS RIVER,GOMBE,CLINKA,45.0,NaN,1.086427e+06,2021,9,NGN,956780.0
269,TP1091963,kristal transport,40.00,Flatbed,2020-09-21 16:03:32.213000+00:00,south west,south west,LAGOS,LAGOS,OTHERS,40.0,NaN,0.000000e+00,2020,9,NGN,280000.0
8390,TP1160529,MoveSmart Logistics,20.00,Covered,2021-09-28 15:00:00+00:00,south west,south west,LAGOS,LAGOS,DETERGENT,20.0,NaN,5.013500e+04,2021,9,NGN,100170.0
7081,TP1158077,MUBARAK SANI KOGUNA,40.00,Covered,2021-09-08 19:18:00+00:00,north west,south west,KANO,LAGOS,OTHERS,40.0,NaN,1.078688e+06,2021,9,NGN,340000.0
77,TP1086416,kristal transport,40.00,Flatbed,2020-08-27 15:17:19.175000+00:00,south west,south west,LAGOS,LAGOS,OTHERS,40.0,8.873,8.873000e-03,2020,8,NGN,280000.0
4072,TP1152854,Alhamdulillah Sufuri Technologies Ltd,30.00,Open,2021-07-30 11:08:00+00:00,south west,south south,LAGOS,EDO,FERTILIZER,30.0,NaN,3.399630e+05,2021,7,NGN,340000.0
2362,TP1138703,Emeka Obi,30.00,Open,2021-04-28 21:11:00+00:00,south west,south west,LAGOS,LAGOS,FLOUR,30.0,NaN,2.957800e+04,2021,4,NGN,87706.0
13150,TP1167649,A S Malik global services limited,30.00,covered,2021-12-05 13:04:00+00:00,south west,south south,LAGOS,RIVERS,BEVERAGES,30.0,NaN,6.396620e+05,2021,12,NGN,550000.0
967,TP1107580,Jenkings Global Limited,30.00,Open,2020-11-08 18:34:00+00:00,north central,north west,KOGI,SOKOTO,COAL,30.0,977.359,9.773590e-01,2020,11,NGN,465000.0

In [101]:
replace_values = {1: 'January', 2: 'February', 3: 'March', 4: 'April', 5: 'May', 6: 'June', 7: 'July', 8: 'August', 9: 'September', 10: 'October', 11: 'November', 12: 'December' }
#trips2021 = trips2021.replace({"months": replace_values})
new_price['month'] = new_price['month'].map(replace_values)

In [102]:
new_price.asset_size.unique()

array([40., 30., 20., 60.,  5., 45., 35., 15., 10., nan,  3., 28.,  2.,
        8., 50., 55.])

In [103]:
new_price.min()  #drop distance = 0, cargoTonnage = 0, amount < 100000
new_price = new_price.loc[~((new_price['asset_size'] == 33000) | (new_price['cargoTonnage'] == 33000) | \
                            (new_price['cargoTonnage'] == 0.0) | (new_price['amount'] <= 1000) | \
                           (new_price['distance'] <= 1)),:]

/home/ec2-user/anaconda3/envs/mxnet_latest_p37/lib/python3.7/site-packages/ipykernel/__main__.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  if __name__ == '__main__':

In [104]:
new_price['asset_type'] = new_price['asset_type'].replace({'covered':'Covered', '2x flatbed':'Flatbed'})
new_price['goodType'] = new_price['goodType'].replace({'OIL/LUBE':'OIL AND GAS', 'CASHEW':'CASHEW NUTS', 'CHEMICAL RAW MATERIAL':'CHEMICAL RAW MATERIALS',\
                                         'CHEMICAL':'CHEMICAL RAW MATERIAL', 'OTHER': 'OTHERS', 'SEMO': 'CORN FLOUR', 'FLOUR':'FLOUR',\
                                        'BEVERAGES':'BEVERAGES AND DRINKS', 'EQUIPMENT': 'EQUIPMENTS', 'FERTILIZER': 'AGROCHEMICAL PRODUCTS',\
                                        'HOUSEHOLD AND OFFICE' : 'HOUSEHOLD ITEMS (AC, FURNITURES,UTENSILS, ETC)', 'AGRO': 'AGROCHEMICAL PRODUCTS'})

In [105]:
new_price['goodType'].unique()

array(['OTHERS', 'FMCG', 'DRINKS', 'MAIZE PELLETS',
       'AGROCHEMICAL PRODUCTS', 'SUGAR', 'FLOUR', 'SOYA MILLS',
       'HOUSEHOLD ITEMS (AC, FURNITURES,UTENSILS, ETC)', 'INDUSTRIAL',
       'RAW MATERIALS', 'CORN FLOUR', 'PASTA', 'BUILDING MATERIALS',
       'SOYABEAN SEEDS', 'EQUIPMENTS', 'BEVERAGES AND DRINKS',
       'WINE AND SPIRIT', 'COAL', 'PHARMACEUTICAL', 'DETERGENT',
       'ANIMAL FEED', 'RICE', 'FISH FEED', 'CHEMICAL RAW MATERIALS',
       'COTTON SEED', 'OIL AND GAS', 'CLINKA', 'POULTRY', 'WHEAT',
       'SORGHUM', 'NOODLES', 'VEDAN', 'SAUSAGE', 'VEGETABLE OIL',
       'SESAME SEED', 'TOMATO PASTE', 'GYPSUM', 'COCOA',
       'CHEMICAL RAW MATERIAL', 'DAIRY PRODUCTS', 'ELECTRICALS',
       'BLACK CARBON'], dtype=object)

In [106]:
new_price.columns

Index(['tripReadId', 'partnerName', 'cargoTonnage', 'asset_type', 'loadedDate',
       'source_region', 'destination_region', 'source', 'destination',
       'goodType', 'asset_size', 'distance', 'totalDistance', 'year', 'month',
       'currency', 'amount'],
      dtype='object')

In [107]:
new_price= new_price[['tripReadId', 'partnerName', 'cargoTonnage', 'asset_type', 'loadedDate', 'source_region',\
                      'destination_region', 'source', 'destination', 'goodType', 'asset_size', 'totalDistance', 'year', 'month', 'currency', 'amount']]

In [108]:
new_price= new_price.dropna()

In [109]:
new_price.head(10)

,tripReadId,partnerName,cargoTonnage,asset_type,loadedDate,source_region,destination_region,source,destination,goodType,asset_size,totalDistance,year,month,currency,amount
0,TP1092434,kristal transport,4.0,Flatbed,2020-09-23 23:51:23.478000+00:00,south west,south west,LAGOS,LAGOS,OTHERS,40.0,0.0,2020,September,NGN,280000.0
1,TP1092433,kristal transport,4.0,Flatbed,2020-09-23 23:47:40.954000+00:00,south west,south west,LAGOS,LAGOS,OTHERS,40.0,0.0,2020,September,NGN,280000.0
2,TP1092247,kristal transport,40.0,Flatbed,2020-09-23 06:42:22.101000+00:00,south west,south west,LAGOS,LAGOS,OTHERS,40.0,0.0,2020,September,NGN,280000.0
3,TP1093081,Gbenguson International Enterprise,30.0,Open,2020-09-26 13:17:52.578000+00:00,south west,south west,LAGOS,LAGOS,FMCG,30.0,0.0,2020,September,NGN,102163.0
4,TP1093472,Gbenguson International Enterprise,30.0,Open,2020-09-28 13:58:05.987000+00:00,south west,south west,LAGOS,LAGOS,FMCG,30.0,0.0,2020,September,NGN,130830.0
5,TP1093078,Gbenguson International Enterprise,30.0,Open,2020-09-26 13:07:49.804000+00:00,south west,south west,LAGOS,LAGOS,FMCG,30.0,0.0,2020,September,NGN,102163.0
6,TP1093476,Gbenguson International Enterprise,30.0,Open,2020-09-28 14:10:54.541000+00:00,south west,south west,LAGOS,LAGOS,FMCG,30.0,0.0,2020,September,NGN,121533.0
7,TP1091442,SRO LOGISTICS LTD,20.0,Covered,2020-09-18 14:37:12.651000+00:00,south west,south south,OGUN,EDO,DRINKS,20.0,0.0,2020,September,NGN,150000.0
8,TP1092251,Deomat Nigeria Limited,30.0,Open,2020-09-23 06:54:03.488000+00:00,south west,south south,LAGOS,DELTA,FMCG,30.0,0.0,2020,September,NGN,301440.0
9,TP1091434,TUNSMAN GLOBAL RESOURCES,30.0,Open,2020-09-18 13:44:28.658000+00:00,south west,south west,LAGOS,OGUN,MAIZE PELLETS,30.0,0.0,2020,September,NGN,210000.0

In [110]:
new_price.shape

(13186, 16)

In [111]:
new_price.isnull().sum()

tripReadId            0
partnerName           0
cargoTonnage          0
asset_type            0
loadedDate            0
source_region         0
destination_region    0
source                0
destination           0
goodType              0
asset_size            0
totalDistance         0
year                  0
month                 0
currency              0
amount                0
dtype: int64

In [112]:
#new_price.value_counts()
valid_df = new_price.query("year==2021 & month == 'December' & totalDistance> 0").sample(20)
valid_df.to_csv('offline_validation.csv')

In [113]:
c_new_price= new_price.query("tripReadId != 'TP1167658' | tripReadId != 'TP1167709' | tripReadId != 'TP1167712' | tripReadId != 'TP1168256' | tripReadId != 'TP1168657' | tripReadId != 'TP1168164'| tripReadId != 'TP1168574' | tripReadId != 'TP1168040' | tripReadId != 'TP1167684' | tripReadId != 'TP1167846' | tripReadId != 'TP1167964'| tripReadId != 'TP1168071' | tripReadId != 'TP1167618' | tripReadId != 'TP1168117' | tripReadId != 'TP1167705' | tripReadId != 'TP1167953'| tripReadId != 'TP1167680' | tripReadId != 'TP1167530' | tripReadId != 'TP1168162' | tripReadId != 'TP1168308'")

In [114]:
c_new_price.columns

Index(['tripReadId', 'partnerName', 'cargoTonnage', 'asset_type', 'loadedDate',
       'source_region', 'destination_region', 'source', 'destination',
       'goodType', 'asset_size', 'totalDistance', 'year', 'month', 'currency',
       'amount'],
      dtype='object')

In [115]:
c_new_price = c_new_price[['tripReadId', 'partnerName','cargoTonnage', 'asset_type', 'loadedDate','source_region', 'destination_region', 'source', 'destination',\
                           'goodType', 'asset_size', 'totalDistance', 'month','currency', 'amount']]

In [116]:
#new_price.to_csv('cleaned_nigeria_1-0-0.csv')
c_new_price.to_csv('cleaned_nigeria_1-0-1.csv')