# Data cleaning and feature engineering

In [25]:
# import libraries
import numpy as np
import pandas as pd

In [26]:
# read the dataframe
df = pd.read_csv('~/Documents/Projects/update_project/My_Best_Projects/Solar_Energy_Project/datasets/raw/solar_ir_abj_60M.csv')

In [27]:
# printout the column names
df.columns

Index(['PeriodEnd', 'PeriodStart', 'Period', 'AirTemp', 'Dhi', 'Dni', 'Ghi',
       'PrecipitableWater', 'RelativeHumidity', 'SurfacePressure',
       'WindDirection10m', 'WindSpeed10m'],
      dtype='object')

In [28]:
# select some features
df = df[['PeriodEnd', 'PeriodStart', 'AirTemp', 'Dhi', 'Dni', 'Ghi',
       'PrecipitableWater', 'RelativeHumidity', 'SurfacePressure',
       'WindDirection10m', 'WindSpeed10m']]

In [29]:
# randomly display 10 rows
df.sample(10)

,PeriodEnd,PeriodStart,AirTemp,Dhi,Dni,Ghi,PrecipitableWater,RelativeHumidity,SurfacePressure,WindDirection10m,WindSpeed10m
10321,2020-11-03T03:00:00Z,2020-11-03T02:00:00Z,22.9,0,0,0,25.7,42.1,960.0,34,1.7
13404,2021-03-11T14:00:00Z,2021-03-11T13:00:00Z,38.1,558,95,640,37.0,25.5,955.0,224,1.6
6495,2020-05-27T17:00:00Z,2020-05-27T16:00:00Z,31.9,13,0,13,49.2,52.6,958.3,353,1.5
9975,2020-10-19T17:00:00Z,2020-10-19T16:00:00Z,26.8,54,135,87,36.8,75.6,958.4,240,1.6
11532,2020-12-23T14:00:00Z,2020-12-23T13:00:00Z,36.4,206,709,716,24.3,18.1,957.9,146,1.0
14205,2021-04-13T23:00:00Z,2021-04-13T22:00:00Z,26.1,0,0,0,33.5,60.1,961.5,190,1.6
7068,2020-06-20T14:00:00Z,2020-06-20T13:00:00Z,25.7,449,239,651,45.5,75.4,962.9,313,1.2
9191,2020-09-17T01:00:00Z,2020-09-17T00:00:00Z,21.8,0,0,0,53.1,95.3,961.4,184,1.9
5943,2020-05-04T17:00:00Z,2020-05-04T16:00:00Z,31.5,123,43,138,53.5,51.1,958.1,180,2.0
17633,2021-09-03T19:00:00Z,2021-09-03T18:00:00Z,22.7,0,0,0,46.4,94.8,960.6,227,1.8

In [30]:
old_names = ['PeriodEnd', 'PeriodStart', 'AirTemp', 'Dhi', 'Dni', 'Ghi','PrecipitableWater', 'RelativeHumidity',
             'SurfacePressure', 'WindDirection10m', 'WindSpeed10m'] 
new_names = ['PeriodEnd','PeriodStart','Temperature', 'DHI', 'DNI', 'Radiation', 'Precipitation', 'Humidity', 
             'Pressure', 'WindDirection', 'WindSpeed']
df.rename(columns = dict(zip(old_names, new_names)), inplace = True)

In [31]:
# display dataframe
df.head()

,PeriodEnd,PeriodStart,Temperature,DHI,DNI,Radiation,Precipitation,Humidity,Pressure,WindDirection,WindSpeed
0,2019-08-31T02:00:00Z,2019-08-31T01:00:00Z,22.0,0,0,0,45.6,88.3,960.4,356,0.8
1,2019-08-31T03:00:00Z,2019-08-31T02:00:00Z,21.8,0,0,0,45.9,88.5,960.0,353,0.6
2,2019-08-31T04:00:00Z,2019-08-31T03:00:00Z,21.5,0,0,0,46.4,89.5,960.2,357,0.4
3,2019-08-31T05:00:00Z,2019-08-31T04:00:00Z,21.3,0,0,0,46.9,90.9,960.9,57,0.3
4,2019-08-31T06:00:00Z,2019-08-31T05:00:00Z,21.6,17,5,18,47.1,91.3,961.7,110,0.6

In [32]:
# show a summary of the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18309 entries, 0 to 18308
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PeriodEnd      18309 non-null  object
 1   PeriodStart    18309 non-null  object
 2   Temperature    18309 non-null  float64
 3   DHI            18309 non-null  int64
 4   DNI            18309 non-null  int64
 5   Radiation      18309 non-null  int64
 6   Precipitation  18309 non-null  float64
 7   Humidity       18309 non-null  float64
 8   Pressure       18309 non-null  float64
 9   WindDirection  18309 non-null  int64
 10  WindSpeed      18309 non-null  float64
dtypes: float64(5), int64(4), object(2)
memory usage: 1.5+ MB

In [33]:
 # interpret columns as appropriate data types to ensure compatibility
df['Radiation']     = df['Radiation'].astype(float)
df['Temperature']   = df['Temperature'].astype(float) # or int
df['Pressure']      = df['Pressure'].astype(float)
df['Humidity']      = df['Humidity'].astype(int) # or int
df['WindDirection'] = df['WindDirection'].astype(float)
df['WindSpeed']     = df['WindSpeed'].astype(float)
df['PeriodStart'] = pd.to_datetime(df['PeriodStart']).dt.to_period('T').dt.to_timestamp()
df['PeriodEnd'] = pd.to_datetime(df['PeriodEnd']).dt.to_period('T').dt.to_timestamp()

/home/josephitopa/anaconda3/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py:1143: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  warnings.warn(

In [34]:
# display dataframe summary
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18309 entries, 0 to 18308
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PeriodEnd      18309 non-null  datetime64[ns]
 1   PeriodStart    18309 non-null  datetime64[ns]
 2   Temperature    18309 non-null  float64
 3   DHI            18309 non-null  int64
 4   DNI            18309 non-null  int64
 5   Radiation      18309 non-null  float64
 6   Precipitation  18309 non-null  float64
 7   Humidity       18309 non-null  int64
 8   Pressure       18309 non-null  float64
 9   WindDirection  18309 non-null  float64
 10  WindSpeed      18309 non-null  float64
dtypes: datetime64[ns](2), float64(6), int64(3)
memory usage: 1.5 MB

In [35]:
# display top 6 rows
df.head(6)

,PeriodEnd,PeriodStart,Temperature,DHI,DNI,Radiation,Precipitation,Humidity,Pressure,WindDirection,WindSpeed
0,2019-08-31 02:00:00,2019-08-31 01:00:00,22.0,0,0,0.0,45.6,88,960.4,356.0,0.8
1,2019-08-31 03:00:00,2019-08-31 02:00:00,21.8,0,0,0.0,45.9,88,960.0,353.0,0.6
2,2019-08-31 04:00:00,2019-08-31 03:00:00,21.5,0,0,0.0,46.4,89,960.2,357.0,0.4
3,2019-08-31 05:00:00,2019-08-31 04:00:00,21.3,0,0,0.0,46.9,90,960.9,57.0,0.3
4,2019-08-31 06:00:00,2019-08-31 05:00:00,21.6,17,5,18.0,47.1,91,961.7,110.0,0.6
5,2019-08-31 07:00:00,2019-08-31 06:00:00,22.8,103,247,179.0,47.2,89,962.6,136.0,0.6

In [36]:
# Create new features(year, month, day) from start and end time of data collection  
df['YearPS'] = pd.to_datetime(df['PeriodStart']).dt.year
df['YearPE'] = pd.to_datetime(df['PeriodEnd']).dt.year

df['MonthPS'] = pd.to_datetime(df['PeriodStart']).dt.month
df['MonthPE'] = pd.to_datetime(df['PeriodEnd']).dt.month

df['HourPS'] = pd.to_datetime(df['PeriodStart']).dt.hour
df['HourPE'] = pd.to_datetime(df['PeriodEnd']).dt.hour

In [37]:
df.head(5)

,PeriodEnd,PeriodStart,Temperature,DHI,DNI,Radiation,Precipitation,Humidity,Pressure,WindDirection,WindSpeed,YearPS,YearPE,MonthPS,MonthPE,HourPS,HourPE
0,2019-08-31 02:00:00,2019-08-31 01:00:00,22.0,0,0,0.0,45.6,88,960.4,356.0,0.8,2019,2019,8,8,1,2
1,2019-08-31 03:00:00,2019-08-31 02:00:00,21.8,0,0,0.0,45.9,88,960.0,353.0,0.6,2019,2019,8,8,2,3
2,2019-08-31 04:00:00,2019-08-31 03:00:00,21.5,0,0,0.0,46.4,89,960.2,357.0,0.4,2019,2019,8,8,3,4
3,2019-08-31 05:00:00,2019-08-31 04:00:00,21.3,0,0,0.0,46.9,90,960.9,57.0,0.3,2019,2019,8,8,4,5
4,2019-08-31 06:00:00,2019-08-31 05:00:00,21.6,17,5,18.0,47.1,91,961.7,110.0,0.6,2019,2019,8,8,5,6

In [38]:
# create a new feature for sunrise using the function below; fill time for sunrise
def time_to_sunrise(row):
    """
    A function for identifying time of sunrise.
    """
    value= 0
    if row['HourPS'] == 4 and row['HourPE'] == 5 and row['Radiation'] > 0:
        value= '05:00:00'
    elif row['HourPS'] == 5 and row['HourPE'] == 6 and row['Radiation'] > 0:
        value= '06:00:00'
    return value

In [39]:
#Create a new column using the function above
df['Sunrise'] = df.apply(time_to_sunrise, axis=1)
df.head(5)

,PeriodEnd,PeriodStart,Temperature,DHI,DNI,Radiation,Precipitation,Humidity,Pressure,WindDirection,WindSpeed,YearPS,YearPE,MonthPS,MonthPE,HourPS,HourPE,Sunrise
0,2019-08-31 02:00:00,2019-08-31 01:00:00,22.0,0,0,0.0,45.6,88,960.4,356.0,0.8,2019,2019,8,8,1,2,0
1,2019-08-31 03:00:00,2019-08-31 02:00:00,21.8,0,0,0.0,45.9,88,960.0,353.0,0.6,2019,2019,8,8,2,3,0
2,2019-08-31 04:00:00,2019-08-31 03:00:00,21.5,0,0,0.0,46.4,89,960.2,357.0,0.4,2019,2019,8,8,3,4,0
3,2019-08-31 05:00:00,2019-08-31 04:00:00,21.3,0,0,0.0,46.9,90,960.9,57.0,0.3,2019,2019,8,8,4,5,0
4,2019-08-31 06:00:00,2019-08-31 05:00:00,21.6,17,5,18.0,47.1,91,961.7,110.0,0.6,2019,2019,8,8,5,6,06:00:00

In [40]:
# create a new feature for sunset using the function below; fill time for sunset
def time_to_sunset(row):
    """
    A function for identifying time of sunset.
    """
    value= 0
    if row['HourPS'] == 17 and row['HourPE'] == 18 and row['Radiation']> 0:
        value= '18:00:00'
    elif row['HourPS'] == 18 and row['HourPE']== 19 and row['Radiation']> 0:
        value= '19:00:00'
    return value

In [41]:
#Create a new column using the function above
df['Sunset'] = df.apply(time_to_sunset, axis=1)

In [42]:
df.Sunset.unique()

array([0, '18:00:00'], dtype=object)

In [43]:
# show summary of our dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18309 entries, 0 to 18308
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PeriodEnd      18309 non-null  datetime64[ns]
 1   PeriodStart    18309 non-null  datetime64[ns]
 2   Temperature    18309 non-null  float64
 3   DHI            18309 non-null  int64
 4   DNI            18309 non-null  int64
 5   Radiation      18309 non-null  float64
 6   Precipitation  18309 non-null  float64
 7   Humidity       18309 non-null  int64
 8   Pressure       18309 non-null  float64
 9   WindDirection  18309 non-null  float64
 10  WindSpeed      18309 non-null  float64
 11  YearPS         18309 non-null  int64
 12  YearPE         18309 non-null  int64
 13  MonthPS        18309 non-null  int64
 14  MonthPE        18309 non-null  int64
 15  HourPS         18309 non-null  int64
 16  HourPE         18309 non-null  int64
 17  Sunrise        18309 non-null  object
 18  Sunset         18309 non-null  object
dtypes: datetime64[ns](2), float64(6), int64(9), object(2)
memory usage: 2.7+ MB

In [44]:
# changing integer values to datetime format
df_new = df.loc[~((df['Radiation'] == 0) & (df['DNI'] == 0) & (df['DHI'] == 0)),:]

In [45]:
# show summary of our dataframe
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9839 entries, 4 to 18304
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PeriodEnd      9839 non-null   datetime64[ns]
 1   PeriodStart    9839 non-null   datetime64[ns]
 2   Temperature    9839 non-null   float64
 3   DHI            9839 non-null   int64
 4   DNI            9839 non-null   int64
 5   Radiation      9839 non-null   float64
 6   Precipitation  9839 non-null   float64
 7   Humidity       9839 non-null   int64
 8   Pressure       9839 non-null   float64
 9   WindDirection  9839 non-null   float64
 10  WindSpeed      9839 non-null   float64
 11  YearPS         9839 non-null   int64
 12  YearPE         9839 non-null   int64
 13  MonthPS        9839 non-null   int64
 14  MonthPE        9839 non-null   int64
 15  HourPS         9839 non-null   int64
 16  HourPE         9839 non-null   int64
 17  Sunrise        9839 non-null   object
 18  Sunset         9839 non-null   object
dtypes: datetime64[ns](2), float64(6), int64(9), object(2)
memory usage: 1.5+ MB

In [46]:
# display 10 random samples of the dataframe
df_new.sample(10)

,PeriodEnd,PeriodStart,Temperature,DHI,DNI,Radiation,Precipitation,Humidity,Pressure,WindDirection,WindSpeed,YearPS,YearPE,MonthPS,MonthPE,HourPS,HourPE,Sunrise,Sunset
11674,2020-12-29 12:00:00,2020-12-29 11:00:00,35.8,430,356,730.0,21.1,16,959.2,221.0,1.2,2020,2020,12,12,11,12,0,0
5669,2020-04-23 07:00:00,2020-04-23 06:00:00,25.3,118,0,118.0,38.1,83,960.2,164.0,1.5,2020,2020,4,4,6,7,0,0
17174,2021-08-15 16:00:00,2021-08-15 15:00:00,25.0,72,0,72.0,51.4,86,958.8,259.0,2.7,2021,2021,8,8,15,16,0,0
14483,2021-04-25 13:00:00,2021-04-25 12:00:00,34.7,230,736,937.0,45.7,40,957.9,192.0,2.4,2021,2021,4,4,12,13,0,0
7929,2020-07-26 11:00:00,2020-07-26 10:00:00,26.7,497,149,640.0,49.3,75,962.9,256.0,1.9,2020,2020,7,7,10,11,0,0
3731,2020-02-02 13:00:00,2020-02-02 12:00:00,35.6,278,719,906.0,12.0,8,961.3,248.0,2.0,2020,2020,2,2,12,13,0,0
3016,2020-01-03 18:00:00,2020-01-03 17:00:00,27.3,4,3,5.0,16.4,18,960.6,247.0,0.7,2020,2020,1,1,17,18,0,18:00:00
12303,2021-01-24 17:00:00,2021-01-24 16:00:00,34.0,103,0,103.0,13.6,12,956.7,148.0,1.3,2021,2021,1,1,16,17,0,0
11583,2020-12-25 17:00:00,2020-12-25 16:00:00,32.9,66,208,109.0,17.4,15,956.2,190.0,0.9,2020,2020,12,12,16,17,0,0
800,2019-10-03 10:00:00,2019-10-03 09:00:00,26.4,318,0,318.0,47.0,78,962.9,177.0,1.0,2019,2019,10,10,9,10,0,0

In [47]:
# convert datetime column of endperiod to just date
df_new['Date'] = pd.to_datetime(df_new['PeriodEnd']).dt.normalize()

<ipython-input-47-1a198fa8ca88>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['Date']= pd.to_datetime(df_new['PeriodEnd']).dt.normalize()

In [48]:
# convert the column (it's a string) to datetime type
dt_series = pd.to_datetime(df_new['Date'])

# create datetime index passing the datetime series
dt_index = pd.DatetimeIndex(dt_series.values)

# 
df_new1 = df_new.set_index(dt_index)

In [49]:
# display first 5 rows
df_new1.head()

,PeriodEnd,PeriodStart,Temperature,DHI,DNI,Radiation,Precipitation,Humidity,Pressure,WindDirection,WindSpeed,YearPS,YearPE,MonthPS,MonthPE,HourPS,HourPE,Sunrise,Sunset,Date
2019-08-31,2019-08-31 06:00:00,2019-08-31 05:00:00,21.6,17,5,18.0,47.1,91,961.7,110.0,0.6,2019,2019,8,8,5,6,06:00:00,0,2019-08-31
2019-08-31,2019-08-31 07:00:00,2019-08-31 06:00:00,22.8,103,247,179.0,47.2,89,962.6,136.0,0.6,2019,2019,8,8,6,7,0,0,2019-08-31
2019-08-31,2019-08-31 08:00:00,2019-08-31 07:00:00,24.2,234,142,296.0,47.8,84,963.3,184.0,0.6,2019,2019,8,8,7,8,0,0,2019-08-31
2019-08-31,2019-08-31 09:00:00,2019-08-31 08:00:00,25.6,323,0,323.0,48.3,81,963.2,216.0,0.8,2019,2019,8,8,8,9,0,0,2019-08-31
2019-08-31,2019-08-31 10:00:00,2019-08-31 09:00:00,26.8,477,0,477.0,48.8,78,962.6,215.0,0.9,2019,2019,8,8,9,10,0,0,2019-08-31

In [50]:
# 
df_new1.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9839 entries, 2019-08-31 to 2021-10-01
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PeriodEnd      9839 non-null   datetime64[ns]
 1   PeriodStart    9839 non-null   datetime64[ns]
 2   Temperature    9839 non-null   float64
 3   DHI            9839 non-null   int64
 4   DNI            9839 non-null   int64
 5   Radiation      9839 non-null   float64
 6   Precipitation  9839 non-null   float64
 7   Humidity       9839 non-null   int64
 8   Pressure       9839 non-null   float64
 9   WindDirection  9839 non-null   float64
 10  WindSpeed      9839 non-null   float64
 11  YearPS         9839 non-null   int64
 12  YearPE         9839 non-null   int64
 13  MonthPS        9839 non-null   int64
 14  MonthPE        9839 non-null   int64
 15  HourPS         9839 non-null   int64
 16  HourPE         9839 non-null   int64
 17  Sunrise        9839 non-null   object
 18  Sunset         9839 non-null   object
 19  Date           9839 non-null   datetime64[ns]
dtypes: datetime64[ns](3), float64(6), int64(9), object(2)
memory usage: 1.6+ MB

In [51]:
# sample daily average for the solar and weather features
df_new1['Daily_radiation'] = df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['Radiation'].mean()
df_new1['Daily_DNI'] = df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['DNI'].mean()
df_new1['Daily_DHI'] = df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['DHI'].mean()
df_new1['Daily_Temp'] = df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['Temperature'].mean()
df_new1['Daily_Precip'] = df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['Precipitation'].mean()
df_new1['Daily_Humidity'] = df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['Humidity'].mean()
df_new1['Daily_Pressure'] = df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['Pressure'].mean()
df_new1['Daily_WindDir'] = df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['WindDirection'].mean()
df_new1['Daily_WindSpeed'] = df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['WindSpeed'].mean()

In [52]:
# display a summary of our dataframe
df_new1.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9839 entries, 2019-08-31 to 2021-10-01
Data columns (total 29 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PeriodEnd        9839 non-null   datetime64[ns]
 1   PeriodStart      9839 non-null   datetime64[ns]
 2   Temperature      9839 non-null   float64
 3   DHI              9839 non-null   int64
 4   DNI              9839 non-null   int64
 5   Radiation        9839 non-null   float64
 6   Precipitation    9839 non-null   float64
 7   Humidity         9839 non-null   int64
 8   Pressure         9839 non-null   float64
 9   WindDirection    9839 non-null   float64
 10  WindSpeed        9839 non-null   float64
 11  YearPS           9839 non-null   int64
 12  YearPE           9839 non-null   int64
 13  MonthPS          9839 non-null   int64
 14  MonthPE          9839 non-null   int64
 15  HourPS           9839 non-null   int64
 16  HourPE           9839 non-null   int64
 17  Sunrise          9839 non-null   object
 18  Sunset           9839 non-null   object
 19  Date             9839 non-null   datetime64[ns]
 20  Daily_radiation  9839 non-null   float64
 21  Daily_DNI        9839 non-null   float64
 22  Daily_DHI        9839 non-null   float64
 23  Daily_Temp       9839 non-null   float64
 24  Daily_Precip     9839 non-null   float64
 25  Daily_Humidity   9839 non-null   float64
 26  Daily_Pressure   9839 non-null   float64
 27  Daily_WindDir    9839 non-null   float64
 28  Daily_WindSpeed  9839 non-null   float64
dtypes: datetime64[ns](3), float64(15), int64(9), object(2)
memory usage: 2.3+ MB

In [53]:
# drop irrelevant features
new_df= df_new1.drop(['PeriodStart', 'YearPS', 'HourPS', 'HourPE', 'Sunrise', 'Sunset', 'MonthPS', 'YearPE'], axis= 1)

In [54]:
# display first 10 rows
new_df.head(10)

,PeriodEnd,Temperature,DHI,DNI,Radiation,Precipitation,Humidity,Pressure,WindDirection,WindSpeed,...,Date,Daily_radiation,Daily_DNI,Daily_DHI,Daily_Temp,Daily_Precip,Daily_Humidity,Daily_Pressure,Daily_WindDir,Daily_WindSpeed
2019-08-31,2019-08-31 06:00:00,21.6,17,5,18.0,47.1,91,961.7,110.0,0.6,...,2019-08-31,248.538462,35.384615,233.0,26.423077,49.384615,77.769231,960.823077,213.769231,0.846154
2019-08-31,2019-08-31 07:00:00,22.8,103,247,179.0,47.2,89,962.6,136.0,0.6,...,2019-08-31,248.538462,35.384615,233.0,26.423077,49.384615,77.769231,960.823077,213.769231,0.846154
2019-08-31,2019-08-31 08:00:00,24.2,234,142,296.0,47.8,84,963.3,184.0,0.6,...,2019-08-31,248.538462,35.384615,233.0,26.423077,49.384615,77.769231,960.823077,213.769231,0.846154
2019-08-31,2019-08-31 09:00:00,25.6,323,0,323.0,48.3,81,963.2,216.0,0.8,...,2019-08-31,248.538462,35.384615,233.0,26.423077,49.384615,77.769231,960.823077,213.769231,0.846154
2019-08-31,2019-08-31 10:00:00,26.8,477,0,477.0,48.8,78,962.6,215.0,0.9,...,2019-08-31,248.538462,35.384615,233.0,26.423077,49.384615,77.769231,960.823077,213.769231,0.846154
2019-08-31,2019-08-31 11:00:00,28.0,605,66,668.0,49.4,73,961.9,204.0,0.7,...,2019-08-31,248.538462,35.384615,233.0,26.423077,49.384615,77.769231,960.823077,213.769231,0.846154
2019-08-31,2019-08-31 12:00:00,29.1,496,0,496.0,49.5,68,961.1,231.0,0.7,...,2019-08-31,248.538462,35.384615,233.0,26.423077,49.384615,77.769231,960.823077,213.769231,0.846154
2019-08-31,2019-08-31 13:00:00,29.4,206,0,206.0,49.5,65,960.0,260.0,0.8,...,2019-08-31,248.538462,35.384615,233.0,26.423077,49.384615,77.769231,960.823077,213.769231,0.846154
2019-08-31,2019-08-31 14:00:00,29.1,98,0,98.0,49.9,67,959.1,266.0,0.6,...,2019-08-31,248.538462,35.384615,233.0,26.423077,49.384615,77.769231,960.823077,213.769231,0.846154
2019-08-31,2019-08-31 15:00:00,28.4,138,0,138.0,50.4,71,958.4,246.0,1.0,...,2019-08-31,248.538462,35.384615,233.0,26.423077,49.384615,77.769231,960.823077,213.769231,0.846154

In [55]:
# show a summary of the dataframe
new_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9839 entries, 2019-08-31 to 2021-10-01
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PeriodEnd        9839 non-null   datetime64[ns]
 1   Temperature      9839 non-null   float64
 2   DHI              9839 non-null   int64
 3   DNI              9839 non-null   int64
 4   Radiation        9839 non-null   float64
 5   Precipitation    9839 non-null   float64
 6   Humidity         9839 non-null   int64
 7   Pressure         9839 non-null   float64
 8   WindDirection    9839 non-null   float64
 9   WindSpeed        9839 non-null   float64
 10  MonthPE          9839 non-null   int64
 11  Date             9839 non-null   datetime64[ns]
 12  Daily_radiation  9839 non-null   float64
 13  Daily_DNI        9839 non-null   float64
 14  Daily_DHI        9839 non-null   float64
 15  Daily_Temp       9839 non-null   float64
 16  Daily_Precip     9839 non-null   float64
 17  Daily_Humidity   9839 non-null   float64
 18  Daily_Pressure   9839 non-null   float64
 19  Daily_WindDir    9839 non-null   float64
 20  Daily_WindSpeed  9839 non-null   float64
dtypes: datetime64[ns](2), float64(15), int64(4)
memory usage: 1.7 MB

In [56]:
# dropping ALL duplicate values exceept the last value
new_df = new_df[~new_df.Date.duplicated(keep = 'last')]

In [57]:
# show the number of rows and columns available
new_df.shape

(763, 21)

In [58]:
# 
new_df.head(10)

,PeriodEnd,Temperature,DHI,DNI,Radiation,Precipitation,Humidity,Pressure,WindDirection,WindSpeed,...,Date,Daily_radiation,Daily_DNI,Daily_DHI,Daily_Temp,Daily_Precip,Daily_Humidity,Daily_Pressure,Daily_WindDir,Daily_WindSpeed
2019-08-31,2019-08-31 18:00:00,24.8,16,0,16.0,51.6,86,959.8,227.0,1.1,...,2019-08-31,248.538462,35.384615,233.000000,26.423077,49.384615,77.769231,960.823077,213.769231,0.846154
2019-09-01,2019-09-01 18:00:00,24.7,17,33,21.0,50.8,87,959.1,163.0,0.9,...,2019-09-01,457.846154,239.076923,284.846154,25.530769,49.538462,82.153846,960.523077,159.615385,1.507692
2019-09-02,2019-09-02 18:00:00,24.7,19,20,21.0,51.4,87,961.0,259.0,0.1,...,2019-09-02,435.000000,221.153846,251.307692,25.469231,50.700000,81.923077,962.100000,232.923077,1.784615
2019-09-03,2019-09-03 18:00:00,25.0,15,0,15.0,50.3,86,960.9,288.0,1.3,...,2019-09-03,369.769231,138.461538,248.692308,25.123077,48.076923,83.000000,962.846154,287.615385,1.815385
2019-09-04,2019-09-04 18:00:00,25.4,15,54,22.0,51.9,86,961.0,227.0,1.1,...,2019-09-04,425.076923,230.923077,286.384615,26.692308,48.838462,76.769231,961.807692,177.538462,1.176923
2019-09-05,2019-09-05 18:00:00,24.7,17,24,19.0,47.0,85,960.8,286.0,0.7,...,2019-09-05,232.846154,2.461538,232.384615,25.423077,48.446154,81.615385,962.030769,199.846154,1.346154
2019-09-06,2019-09-06 18:00:00,25.5,15,11,16.0,49.6,85,961.0,189.0,0.9,...,2019-09-06,528.692308,437.000000,180.153846,26.892308,45.500000,73.923077,962.361538,165.923077,1.153846
2019-09-07,2019-09-07 18:00:00,24.8,14,49,20.0,48.6,88,961.7,265.0,1.4,...,2019-09-07,421.076923,217.769231,268.000000,25.292308,49.623077,84.000000,962.646154,246.923077,1.930769
2019-09-08,2019-09-08 18:00:00,23.2,13,26,16.0,52.5,92,963.3,278.0,2.0,...,2019-09-08,422.076923,151.692308,311.769231,24.238462,51.961538,87.692308,963.769231,240.307692,1.907692
2019-09-09,2019-09-09 18:00:00,23.7,14,25,16.0,52.2,91,963.1,54.0,0.3,...,2019-09-09,438.076923,176.076923,295.923077,23.946154,48.976923,86.846154,963.561538,226.846154,1.907692

In [59]:
# list out the column names
new_df.columns

Index(['PeriodEnd', 'Temperature', 'DHI', 'DNI', 'Radiation', 'Precipitation',
       'Humidity', 'Pressure', 'WindDirection', 'WindSpeed', 'MonthPE', 'Date',
       'Daily_radiation', 'Daily_DNI', 'Daily_DHI', 'Daily_Temp',
       'Daily_Precip', 'Daily_Humidity', 'Daily_Pressure', 'Daily_WindDir',
       'Daily_WindSpeed'],
      dtype='object')

In [61]:
# select column features
final_df= new_df[['MonthPE', 'Date','Daily_Temp','Daily_Precip', 'Daily_Humidity', 'Daily_Pressure',\
                  'Daily_WindDir','Daily_WindSpeed','Daily_DNI', 'Daily_DHI','Daily_radiation']]

In [62]:
# print the first 5 rows
final_df.head()

,MonthPE,Date,Daily_Temp,Daily_Precip,Daily_Humidity,Daily_Pressure,Daily_WindDir,Daily_WindSpeed,Daily_DNI,Daily_DHI,Daily_radiation
2019-08-31,8,2019-08-31,26.423077,49.384615,77.769231,960.823077,213.769231,0.846154,35.384615,233.000000,248.538462
2019-09-01,9,2019-09-01,25.530769,49.538462,82.153846,960.523077,159.615385,1.507692,239.076923,284.846154,457.846154
2019-09-02,9,2019-09-02,25.469231,50.700000,81.923077,962.100000,232.923077,1.784615,221.153846,251.307692,435.000000
2019-09-03,9,2019-09-03,25.123077,48.076923,83.000000,962.846154,287.615385,1.815385,138.461538,248.692308,369.769231
2019-09-04,9,2019-09-04,26.692308,48.838462,76.769231,961.807692,177.538462,1.176923,230.923077,286.384615,425.076923

In [63]:
# show the number of rows and column
final_df.shape

(763, 11)

In [64]:
# save cleaned dataset
final_df.to_csv('~/Documents/Projects/update_project/My_Best_Projects/Solar_Energy_Project/datasets/cleaned/cleaned_solar_irradiation.csv')